### ISSUE TITLE
Unable to add Moebot integration after reinstall

### ISSUE THREAD

**Issue by mickcomp** [Whytey/moebot-hass-integration#36]
I had some broken icons after moving from the vacuum card to lawn mower card so i decided to remove both HACS and the HA integration and start again.  I am now unable to add the moebot in the HA integration with the device id IP and local Key

`Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 3:40:48 PM (1 occurrences)
Last logged: 3:40:48 PM

Detected blocking call to sleep with args (5,) inside the event loop by custom integration 'moebot' at custom_components/moebot/config_flow.py, line 35: d = MoeBot(data["device_id"], data["ip_address"], data["local_key"]) (offender: /usr/local/lib/python3.12/site-packages/tinytuya/core.py, line 993: time.sleep(self.socketRetryDelay)), please create a bug report at https://github.com/Whytey/moebot-hass-integration/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#sleep Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle resp = await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 415, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/moebot/config_flow.py", line 60, in async_step_user info = await validate_input(self.hass, user_input) File "/config/custom_components/moebot/config_flow.py", line 35, in validate_input d = MoeBot(data["device_id"], data["ip_address"], data["local_key"])`

**Comment by Whytey** [comment]
Hmmm, that's a bit strange.  Are you specifying the IP address of the mower (or using AUTO)?  Have you confirmed that it is the current IP address that is assigned - if you're running DHCP then the IP address of the client (the mower) can change sometimes.

**Comment by mickcomp** [comment]
picked the ip out form my router and its set to static anyway. i can control the mower using the tuya app ok.

**Comment by Whytey** [comment]
What version of home assistant are you running?  I can't see if this is a WARNING log message or an ERROR.  I would have thought the former - and thus not actually the cause of any problems.

**Comment by mickcomp** [comment]
2024.7.2

**Comment by Whytey** [comment]
Thanks.

I have just reviewed the tinytuya code being called out.  I am pretty sure that what you are seeing is a warning and isn't the issue preventing you from adding the device.

I wonder if you could:

1. Enable debug logging for pymoebot .
2. Re-attempt to add the Moebot
3. Upload the actual homeassistant.log from your server.

**Comment by mickcomp** [comment]
[home-assistant_2024-07-19T11-43-26.687Z.log.zip](https://github.com/user-attachments/files/16311407/home-assistant_2024-07-19T11-43-26.687Z.log.zip)
Let me know if you need anything else.

**Comment by mickcomp** [comment]
![image](https://github.com/user-attachments/assets/f2e1ac64-22d0-47b2-9986-c980b4868f71)
Error i get

[home-assistant_2024-07-20T03-10-29.474Z.log](https://github.com/user-attachments/files/16318641/home-assistant_2024-07-20T03-10-29.474Z.log)

Also tried removing moebot  HACS integration and reinstalled, tried again with the same result. 

Double checked my device properties from tuya dev website also.

**Comment by Whytey** [comment]
Reproduced on the latest version of home-assistant - will try and resolve! :cry:

**Comment by Whytey** [comment]
Problem has been caused by https://github.com/home-assistant/core/pull/118561 .  Strangely, the error is logged as a warning.

**Comment by Whytey** [comment]
The logging level has been reported as an issue in Home Assistant core.  I expect this issue to be logged as an 'Error'.  https://github.com/home-assistant/core/issues/122248

**Comment by Whytey** [comment]
Resolved by 0.3.1

**Comment by mickcomp** [comment]
can confirm its now working.   I still have duplicate moebot entries and a broken icon. 
![image](https://github.com/user-attachments/assets/3f569b73-4840-4e67-9ae7-b8b0528a57c0)

**Comment by Whytey** [comment]
Glad it's working.

That's not duplicates, one is a vacuum component (per previous versions)
and the other is the new lawn mower component. The vacuum will be removed
in future versions. My recommendation is to disable the vacuum component.

For the icon, I understand that the front-end caches the icons, it will fix
itself in the next several hours to a day as the cached entry gets
refreshed.
